### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by crontable** [sannimdev/rn-sms-sender#5]
## 유틸 프로그램
- [ ] 휴대폰번호 체크 프로그램 테스트 만들기
- [ ] 테스트 코드 작성 후 도메인 코드 리팩터링

## 본 프로그램
- [ ] 이미지 파일 첨부 기능
- [ ]
